server:
  port: 8081
  servlet:
    context-path: /
spring:
  application:
    name: fileTransferConsumer
nacos:
  config:
    server-addr: 127.0.0.1:8848
  discovery:
    server-addr: 127.0.0.1:8848
