server:
  port: 9093
  servlet:
    context-path: /
spring:
  application:
    name: fileTransferProvider3
  dynamic:
    tp:
      enabled: true
      enabledBanner: true
      nacos:
        dataId: fileTransferProvider-default.yml
        group: DEFAULT_GROUP
      executors:
        - threadPoolName: myDtpExecutor
          corePoolSize: 4
          maximumPoolSize: 10
          queueCapacity: 5
          keepAliveTime: 200
          allowCoreThreadTimeOut: false

nacos:
  config:
    server-addr: 127.0.0.1:8848
  discovery:
    server-addr: 127.0.0.1:8848

